### PR TITLE
Add Admin page and functionality

### LINKED ISSUE #14: Admin view reports on usage (with filtering)
Filter by post views charts of post views

### LINKED ISSUE #15: Enable/disable users

### LINKED ISSUE #16: Search for user by name, email or post
On the admin page have a search

### LINKED ISSUE #17: Visual display of updates, etc (site usage charts, etc)
- [x] #18

- [x] #19

- [x] #20

### LINKED ISSUE #18: Chart with the amount of user registrations/day (from database field)

### LINKED ISSUE #19: Chart with post views.

### LINKED ISSUE #20: Chart of views/category.

### LINKED ISSUE #21: Admin Page
Make an admin page

### PR DESCRIPTION
**Pull request by robertyac**
image

everything here works, disabling prevents from commenting or posting.

### CODE REVIEW

**Comment by robertyac** [comment]
Note to myself: `ALTER TABLE User ADD COLUMN IsEnabled BOOLEAN DEFAULT TRUE;` for server

**Comment by robertyac** [comment]
image
Added chart for user registrations per day

**Comment by robertyac** [comment]
https://github.com/robertyac/FivePoint5/assets/112982183/0a28ca5c-a7e5-4fb3-9870-e105bea819c4

**Review by Davis245 — APPROVED** [review]
Looks really good! Thanks Rob.

**Comment by robertyac** [comment]
Merged activity-tracking branch that dave did into here! Works well.

**Pull request merged**
